##numpy
Numpy is a python library,was created in 2005 by Travis Oliphant.
Numpy is used for working with arrays
numpy is short for "numerical python".
50x faster than traditional python list.

In [1]:
#impoting numpy library
import numpy as np
arr1=np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


#different way to create numpy array

In [3]:
#to create an ndarray , we can pass a list , tuple or other array like object
#create 2D array
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [4]:
#to see the dimension
print(arr3.ndim)

2


In [5]:
#create 3D array
arr4=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr4)
print(arr4.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [6]:
#numpy array indexing
arr5=np.array([1,2,3,4,5])
print(arr5[2])

3


In [9]:
print(arr5[0:3])
print(arr5[-1])
print(arr5[-2:-1])


[1 2 3]
5
[4]


In [10]:
#Get third and fourth elements from the following array and add them.
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [13]:
#Access the element on the first row, second column
import numpy as np

arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('2nd element on 1st row:',arr[0,1])
print('5nd element on 2nd row:',arr[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row: 2
5nd element on 2nd row: 10


In [15]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])
print(arr[0,0,0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
1


In [16]:
#negative indexing
#print the last element from the 2nd dim:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('Last element from 2nd dim:',arr[1,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim: 10


In [21]:
#slice elements from index 1 to index 5 from the following array:
import numpy as np
arr= np.array([10,20,30,40,50,60,75])
print(arr[1:5])
#slice elements from index 4 to the end of the array:
print(arr[4:])
#slice elements from beginning to index 4(not included):
print(arr[:4])
#negative slicing
print(arr[-3:-1])
# use step value to determine the step of slicing
print(arr[1:5:2])
#return every other element from the entire array
print(arr[::2])

[20 30 40 50]
[50 60 75]
[10 20 30 40]
[50 60]
[20 40]
[10 30 50 75]


In [24]:
#slicing 2d array
import numpy as np
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
# from both elements return index 2
print(arr[0:2,2])
#from both elements slice index 1 to index 4(not included),this will return a 2d array
print(arr[0:2,1:4])


[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


#DATA TYPES IN NUMPY
Numpy has some extra data types , and refer to data types with one character, like i for integers, u for unsigned integers etc.

###i-integer
###b-boolean
###u-unsigned integer
###f- float
###c-complex float
###etccc....

In [28]:
#create an array with data type string
import numpy as np
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [30]:
#create an array with data type integer
import numpy as np
arr=np.array([1,2,3,4],dtype='i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [29]:
#create an array with data type 4 byte integer
import numpy as np
arr=np.array([1,2,3,4],dtype='4i')
print(arr)
print(arr.dtype)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
int32


In [31]:
#change datatype from float to integer by using 'i' as parameter value
import numpy as np
arr = np.array([1.1,1.2,3.1])
newarr= arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 1 3]
int32


#Numpy array copy vs view
the main difference between a copy and a view of an array is that the copy is a new array ,and the view is just a view of the original array.

In [33]:
# make a copy , change the original array,and display both arrays:
import numpy as np
arr= np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [35]:
# make a view , change the original array,and display both arrays:
import numpy as np
arr= np.array([1,2,3,4,5])
print("original array",arr)
x=arr.view()
arr[0]=42
print(arr)
print(x)

original array [1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


#Numpy Array Shape:
the shape of an array is the number of elements in each dimension

In [36]:
#print the shape od 2D array
import numpy as np
arr=np.array([[1,2,3,4,],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [37]:
# array reshaping
#reshaping from 1d to 2d
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#FLATTENING THE ARRAY
flattening array means converting a multidimensional array into 1d array

In [38]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr= arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [ ]:
#Numpy array iterating
#iterating means going through elements one by one
