# Array creation and properties

In [1]:
#1 Create a NumPy array from [10, 20, 30, 40, 50]. Display its shape, size, and data type.
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr.shape)
print(arr.size)
print(arr.dtype)

(5,)
5
int64


In [4]:
#2 Create a 3 × 4 array containing numbers from 1 to 12.
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
#3 Create an array of zeros, an array of ones, and an identity matrix.
import numpy as np
a=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(a)
b=np.array([[0,0,0],[0,0,0],[0,0,0]])
print(b)
c=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(c)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [7]:
#4 Generate all even numbers between 10 and 50 using np.arange().
import numpy as np
e=np.arange(10,51,2)
print(e)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [8]:
#5 Create an array of 10 equally spaced numbers between 0 and 1 using np.linspace().
import numpy as np

arr = np.linspace(0, 1, 10)

print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


#Array Arithmetic

In [9]:
#6 Given two NumPy arrays, perform element-wise addition, subtraction, multiplication,and division.
import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 5, 8])

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


In [10]:
#7 Calculate the square and cube of every element in a NumPy array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Square:", np.square(arr))
print("Cube:", np.power(arr, 3))

Square: [ 1  4  9 16 25]
Cube: [  1   8  27  64 125]


In [11]:
#8 Increase every element of an array by 15%.
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr * 1.15)

[11.5 23.  34.5 46.  57.5]


In [12]:
#9 Given two arrays, find their element-wise maximum and minimum.
import numpy as np
arr1=[1,2,3,4,5]
arr2=[6,7,8,9,10]
print(np.maximum(arr1,arr2))
print(np.minimum(arr1,arr2))

[ 6  7  8  9 10]
[1 2 3 4 5]


#Indexing & Slicing

In [13]:
#10 Create an array from 0 to 20 and extract the first five elements, last five elements,
#elements from index 5 to 15, and every second element.
import numpy as np
arr=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
print(arr[:6])
print(arr[15:])
print(arr[5:16])
print(arr[::2])

[1, 2, 3, 4, 5, 6]
[16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [15]:
#11 Replace the first five elements of an array with 100.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
arr[:5]=100
print(arr)


[100 100 100 100 100   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


In [16]:
#12 Create an array and demonstrate the difference between a slice/view and a copy.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# View
view = arr[1:4]
view[0] = 100

print("Original array after view:", arr)

# Copy
copy = arr[1:4].copy()
copy[0] = 200

print("Original array after copy:", arr)
print("Copy:", copy)

Original array after view: [  1 100   3   4   5]
Original array after copy: [  1 100   3   4   5]
Copy: [200   3   4]


In [17]:
#13 Reverse a NumPy array using slicing.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

reverse = arr[::-1]

print(reverse)

[10  9  8  7  6  5  4  3  2  1]


# 2-D Array Indexing & Slicing

In [18]:
#14 Create the matrix and extract the second row, third column, and element 50.

import numpy as np

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Second row:", matrix[1])
print("Third column:", matrix[:, 2])
print("Element 50:", matrix[1, 1])

Second row: [40 50 60]
Third column: [30 60 90]
Element 50: 50


In [19]:
#15 Extract the sub-matrix [[20,30],[50,60]].

import numpy as np

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

sub_matrix = matrix[0:2, 1:3]

print(sub_matrix)

[[20 30]
 [50 60]]


In [20]:
#16 Create a 5 × 5 matrix containing 1–25 and extract the first row, last column,
# middle element, and top-left 3 × 3 matrix.

import numpy as np

matrix = np.arange(1, 26).reshape(5, 5)

print("Matrix:")
print(matrix)

print("First row:", matrix[0])
print("Last column:", matrix[:, -1])
print("Middle element:", matrix[2, 2])
print("Top-left 3 × 3 matrix:")
print(matrix[0:3, 0:3])

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Middle element: 13
Top-left 3 × 3 matrix:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


# Reshaping & Transpose

In [21]:
#17 Create an array containing 1–12 and reshape it into a 3 × 4 matrix.

import numpy as np

arr = np.arange(1, 13)

matrix = arr.reshape(3, 4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
#18 Reshape a 1-D array into a 2 × 5 matrix.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

matrix = arr.reshape(2, 5)

print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
#19 Convert a 3 × 4 matrix into a 4 × 3 matrix using transpose.

import numpy as np

matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

transposed = matrix.T

print("Original matrix:")
print(matrix)

print("Transposed matrix:")
print(transposed)

Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed matrix:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [24]:
#20 Use transpose() and swapaxes() on a 3-D array.

import numpy as np

arr = np.arange(1, 25).reshape(2, 3, 4)

print("Original array:")
print(arr)

print("\nUsing transpose():")
print(arr.transpose(2, 1, 0))

print("\nUsing swapaxes():")
print(arr.swapaxes(0, 2))

Original array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Using transpose():
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]

Using swapaxes():
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]
