create a one dimensional array

In [ ]:
import numpy as np
marks=np.array([91,82,73,64,55])
print(marks)

create a two dimensional array

In [ ]:
import numpy as np
marks=np.array([[11,22,33],[54,65,76]])
print(marks)


[[11 22 33]
 [54 65 76]]


create a three dimensional array

In [ ]:
import numpy as np
marks=np.array([[[11,22,33],[54,65,76]],[[23,45,63],[23,54,67]]])
print(marks)

[[[11 22 33]
  [54 65 76]]

 [[23 45 63]
  [23 54 67]]]


In [ ]:
print(marks.ndim)
print(marks.shape)

3
(2, 2, 3)


In [ ]:
arr1=np.zeros((3,4))
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr=np.zeros((3,4,5))
print(arr)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
arr2=np.arange(1,11)
print(arr2)
arr3=np.arange(2,21,2)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
print(arr3.ndim)
print(arr3.shape)
print(arr3.dtype)
print(arr3.size)
arr4=np.array([23.5,55,65,45.6])
print(arr4.dtype)

1
(10,)
int64
10
float64


In [ ]:
arr5=np.array([10,20,30,40,50])
print(arr5[2])
print(arr5[-3])

30
30


In [ ]:
arr6=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print("Element present in row 0 column 2 =",arr6[0,2])
print("Element present in row 1 column 4 =",arr6[1,4])

Element present in row 0, column 2 = 3
Element present in row 1 column 4 = 6


In [ ]:
#reshaping
arr7=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr7.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#flattening
arr8=np.array([[1,2],[3,4],[5,6]])
newarr1=arr8.flatten()
print(newarr1)

[1 2 3 4 5 6]


In [ ]:
#mathemical operations
m=np.array([10,20,30,40,50,60])
print("adding 5 mark",m+5)
print(m-5)
print(m*5)
print(m/5)
print(m%5)


adding 5 mark [15 25 35 45 55 65]
[ 5 15 25 35 45 55]
[ 50 100 150 200 250 300]
[ 2.  4.  6.  8. 10. 12.]
[0 0 0 0 0 0]


In [ ]:
#operations between two arrays
a11=np.array([1,2,3,4,5])
b11=np.array([6,7,8,9,10])
print(a11+b11)
print(a11-b11)
print(a11*b11)
print(a11/b11)
print(a11**b11)
print(a11//b11)
print(a11%b11)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[      1     128    6561  262144 9765625]
[0 0 0 0 0]
[1 2 3 4 5]


In [ ]:
#aggregation function
#min,max,mean,sum,cumsum
arr10=np.array([10,20,30,40,50,60])
print(arr10.min())
print(arr10.max())
print(arr10.mean())
print(arr10.sum())
print(arr10.cumsum())


10
60
35.0
210
[ 10  30  60 100 150 210]


In [ ]:
#day1=10 patients
#day2=12 patients
#day3=15 patients
#day4=10 patients
#day5=7 patients
p=np.array([10,12,15,10,7])
print(p.cumsum())
print(np.sort(p))

[10 22 37 47 54]
[ 7 10 10 12 15]


In [ ]:
#concatenation
r=np.concatenate((a11,b11))
print(r)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#filtering in array
print(p)
re=p[p>=11]
print(re)

[10 12 15 10  7]
[12 15]


In [ ]:
#where function
ma=np.array([35,43,21,45,67,66,53,12,34,54,56,23])
o=np.where(ma<=50)
print(o)

(array([ 0,  1,  2,  3,  7,  8, 11]),)


In [48]:
#flip/reverse
u=np.array([10,20,30,40,50,60])
rev=np.flip(u)
print(rev)

[60 50 40 30 20 10]


In [49]:
#transpose
mar=np.array([[12,34,45,23],[34,45,22,67],[76,54,45,65]])
print(mar)
j=np.transpose(mar)
print(j)

[[12 34 45 23]
 [34 45 22 67]
 [76 54 45 65]]
[[12 34 76]
 [34 45 54]
 [45 22 45]
 [23 67 65]]
